spring:
  application:
    name: i18demo
  datasource:
    url: jdbc:h2:mem:./test;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=USER,YEAR,DATE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.json
  h2:
    console:
      enabled: true
